apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: drisdary/django-app:version-16
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: "sqlserver.database.windows.net"
        - name: DATABASE_USER
          value: "username"
        - name: DATABASE_PASSWORD
          value: "password"
        - name: DATABASE_NAME
          value: "my_db"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - django-app
              topologyKey: "kubernetes.io/hostname"


---
apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: django-app



---
apiVersion: v1
kind: Service
metadata:
  namespace: "default"
  name: my-service
spec:
  type: ExternalName
  externalName: sqlsvr214.database.windows.net