name: Djnago-app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python Setup
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v3
          -
            name: QEMU
            uses: docker/setup-qemu-action@v2
          -
            name: Build
            uses: docker/setup-buildx-action@v2
          -
            name: Login
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
          -
            name: Build and Push
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: drisdary/django-app:version-${{ github.run_number }}

  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'DrisDary/django_app_2_containers/k8_manifests/djangoapp.yaml'
          token: ${{ secrets.GIT_PASSWORD }}
      - name: image update
        run: |
          git config --global user.name "FIRST_NAME LAST_NAME"
          git config --global user.email "MY_NAME@example.com"
          pwd
          cat djangoapp.yaml
          pwd
          sed -i "s+drisdary/django-app.*+drisdary/django-app:version-$RUN_NUMBER+g" djangoapp.yaml
          cat djangoapp.yaml
          git add .
          git commit -m 'Release number : ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}